version: '3.9'

services:
  wiki-dev:
    build:
      context: ./
      dockerfile: Dockerfile_dev
    container_name: wiki-dev
    volumes:
        - './:/workspace'
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    entrypoint: mkdocs serve --dev-addr 0.0.0.0:8000 --watch-theme