# Project Information
site_name: 117503445 Wiki
site_description: 117503445 的个人 WIKI
site_author: '117503445'
site_url: https://wiki.117503445.top
strict: false

# Repository
repo_name: '117503445/wiki'
repo_url: 'https://github.com/117503445/wiki'

# Copyright
copyright: 'Copyright &copy; 2020 - 2023 117503445'

theme:
  name: material
  language: zh
  palette:
    primary: black
    accent: red
  icon:
    repo: fontawesome/brands/github-alt
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  font:
    text: Microsoft YaHei
    code: Consolas
  features:
    - content.code.copy
plugins:
  - search
  - git-revision-date-localized
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences